# Conda environment for reducing fermi data
name: snakemake-workflow-chandra

channels:
  - conda-forge
  - bioconda
  
variables:
  PYTHONNOUSERSITE: "1"
  
dependencies:
  - python=3.9
  - snakemake>=6.4.1
  - pydantic>=1.9.0
  - astropy>=5.2
  - regions>=0.5
  - jupyter