# Conda environment for reducing fermi data
name: snakemake-workflow-chandra

channels:
  - conda-forge
  - bioconda
  - https://cxc.cfa.harvard.edu/conda/ciao
  
variables:
  PYTHONNOUSERSITE: "1"
  
dependencies:
  - python=3.9
  - snakemake>=7.25.1
  - pydantic<2.0
  - astropy<6.0
  - regions>=0.5
  - ciao=4.16
  - sherpa=4.16
  - ciao-contrib
  - caldb_main
  - marx
  - jupyter
