# GitHub Actions workflow for testing and continuous integration.
#
# This file performs testing using tox and tox.ini to define and configure the test environments.

name: CI tests

on:
  push:
    branches:
    - main  # GitHub now defaults to 'main' as the name of the primary branch. Change this as needed.
  #  tags: # run CI if specific tags are pushed
  pull_request:
    # branches: # only build on PRs against 'main' if you need to further limit when CI is run.
    #    - main

jobs:
  # Github Actions supports ubuntu, windows, and macos virtual environments:
  # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
  ci_tests:
    name: CI tests
    runs-on: ubuntu-latest
    env:
      MARX_ROOT: /usr/share/miniconda3/envs/snakemake-workflow-chandra
      CACHE_NUMBER: 0
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: snakemake-workflow-chandra
    - name: Cache conda environment
      uses: actions/cache@v4
      with:
        path: ${{ env.CONDA }}/envs
        key:
          conda-${{ runner.os }}--${{ runner.arch }}--${{hashFiles('environment.yaml') }}-${{ env.CACHE_NUMBER }}
      id: cache
    - name: Update environment
      run:
        conda env update -f environment.yaml
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Run tests
      shell: bash -l {0}
      run: |
        snakemake -c2 --use-conda --conda-frontend conda